SET INTEGRITY FOR tags OFF;
alter table tags add COLUMN upperName GENERATED ALWAYS AS (UPPER(name));
SET INTEGRITY FOR tags IMMEDIATE CHECKED FORCE GENERATED;
CREATE unique INDEX IDX_TAG_NAME_CTX_TYPE ON tags (upperName, contextItemName, type);
SET INTEGRITY FOR ITEM_TAGS IMMEDIATE CHECKED;
